# Generated by Django 5.1.7 on 2025-04-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_logged_in",
            field=models.BooleanField(default=False, verbose_name="登录状态"),
        ),
    ]
