# Generated by Django 5.1.7 on 2025-04-12 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="作业标题")),
                ("description", models.TextField(verbose_name="作业描述")),
                ("deadline", models.DateTimeField(verbose_name="截止时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "作业",
                "verbose_name_plural": "作业",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="课程名称")),
                ("description", models.TextField(blank=True, verbose_name="课程描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
            },
        ),
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="资源标题")),
                (
                    "file",
                    models.FileField(
                        upload_to="course_resources/", verbose_name="资源文件"
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("ppt", "PPT"),
                            ("document", "文档"),
                            ("video", "视频"),
                            ("other", "其他"),
                        ],
                        max_length=10,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "upload_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
            ],
            options={
                "verbose_name": "课程资源",
                "verbose_name_plural": "课程资源",
            },
        ),
        migrations.CreateModel(
            name="AssignmentSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="assignment_submissions/", verbose_name="作业文件"
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="得分"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="评语")),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="courses.assignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "作业提交",
                "verbose_name_plural": "作业提交",
            },
        ),
    ]
