# Generated by Django 5.1.7 on 2025-04-12 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="last_graded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="最后评分时间"
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="last_graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="assignmentsubmission",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "已提交"),
                    ("graded", "已评分"),
                    ("pending", "待处理"),
                ],
                default=None,
                max_length=13,
                verbose_name="状态",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[("active", "进行中"), ("archived", "已结束")],
                default="active",
                max_length=10,
                verbose_name="课程状态",
            ),
        ),
        migrations.CreateModel(
            name="GradeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField(verbose_name="得分")),
                ("comment", models.TextField(blank=True, verbose_name="评语")),
                (
                    "graded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="评分时间"),
                ),
                (
                    "graded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading_histories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_histories",
                        to="courses.assignmentsubmission",
                    ),
                ),
            ],
            options={
                "verbose_name": "评分历史",
                "verbose_name_plural": "评分历史",
                "ordering": ["-graded_at"],
            },
        ),
    ]
