# Generated by Django 5.1.7 on 2025-04-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_assignmentsubmission_last_graded_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("basic", "基础知识"),
                    ("data_structure", "数据结构"),
                    ("algorithm", "算法"),
                    ("advanced", "高级主题"),
                ],
                default="basic",
                max_length=20,
                verbose_name="章节分类",
            ),
        ),
    ]
