# Generated by Django 5.1.7 on 2025-04-13 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_coursecontent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="chapter",
            field=models.CharField(
                choices=[
                    ("uncategorized", "未分类"),
                    ("basic", "基础知识"),
                    ("data_structure", "数据结构"),
                    ("algorithm", "算法"),
                    ("advanced", "高级主题"),
                ],
                default="uncategorized",
                max_length=20,
                verbose_name="章节分类",
            ),
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="章节名称")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "课程章节",
                "verbose_name_plural": "课程章节",
                "ordering": ["order"],
            },
        ),
    ]
